""" Module responsible for generating shaders using simple grammar"""
from simplegrammar import SimpleGrammar
from pcgshader.glslviewer import GlslViewer

import time


def generate(target_shader, target_file):
    """
        generate
    """
    shader = SimpleGrammar() \
        .set_text("#main_structure#")\
        .add_tag("main_structure", [
            """
uniform float u_time;
uniform vec2 u_mouse;
uniform vec2 u_resolution;

void main (void) {
    gl_FragColor = vec4(0.01, 0.01, 0.01, 1.0);
    vec2 st = gl_FragCoord.xy/u_resolution.xy;
    vec3 color = vec3(0.0, 0.0, 0.0);
    #shader_code#
    gl_FragColor.xyz = color;
}
            """
        ])\
        .add_tag("shader_code", [
            "#uv_based_code#"
        ])\
        .add_tag("uv_based_code", [
            """
color += vec3(#random_number#, #random_number#, #random_number#);
            """,
            """
color *= vec3(min(max(#random_number#, 0.01), 0.99), min(max(#random_number#, 0.01), 0.99), min(max(#random_number#, 0.01), 0.99));
            """,
            """
if (#uv_based_condition#)
{
    #uv_based_code#
} else {
    #uv_based_code#
}
            """,
            """
color += vec3(#uv_based_value#, #uv_based_value#, #uv_based_value#);
            """,
            """
color *= vec3(min(max(#uv_based_value#, 0.01), 0.99), min(max(#uv_based_value#, 0.01), 0.99), min(max(#uv_based_value#, 0.01), 0.99));
            """,
            """
#uv_based_code#
#uv_based_code#
            """
        ])\
        .add_tag("uv_based_value", [
            "length(st - vec2(#random_number#, #random_number#))",
            "length(vec2(#uv_based_value#, #uv_based_value#) - vec2(#random_number#, #random_number#))",
            "#random_number# * max(st.x, st.y)",
            "#random_number# * max(#uv_based_value#, #uv_based_value#)",
            "#random_number# * st.x",
            "#random_number# * st.y",
            "#random_number# * st.x + #random_number# * st.y",
            "#random_number# * sin(#uv_based_value#)",
        ])\
        .add_tag("uv_based_condition", [
            "#uv_based_value# > #random_number#",
            "#uv_based_value# < #random_number#",
            "#uv_based_value# > #random_number# && #uv_based_value# < #random_number#",
            "abs(#uv_based_value# - #random_number#) < #random_number#",
        ])\
        .add_tag("random_number", [
            "0.1", "-0.3", "0.4", "0.01", "0.77", "3.14", "0.00001", "0.5", "0.99", "0.25"
        ])

    shader = """
#ifdef GL_ES
precision mediump float;
#endif
    """ + str(shader)

    print("Shader generated by simple grammar:\n%s" % (shader,))

    shader_path = target_shader

    with open(shader_path, 'w') as shader_file:
        shader_file.write(str(shader))

    shader_viewer = GlslViewer(shader_path, {
        'output': target_file,
        # 'headless': True,
        'verbose': True,
        'size': 500,
        'extra_arguments': '-s 5'
    })
    shader_viewer.run()
    # shader_viewer.start()
    # shader_viewer.stop()
